name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to destroy (dev or prod)'
        required: true
        default: 'dev'   

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH public key
        run: echo "${{ secrets.SSH_PUBLIC_KEY }}" > terraform-azure-vm/id_rsa.pub

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: terraform-azure-vm
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: terraform-azure-vm
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform destroy -auto-approve -var-file="envs/${{ github.event.inputs.env }}.tfvars" -var="ssh_public_key_path=../id_rsa.pub"
